
build:
  version: "2.0"

cards:
  message: "welcome to bankAccountManagement cards related prod APIs"
  contactDetails:
    name : "saroj khatiwada"
    email : "sarojkhatiwada1999@gmail.com"
  onCallSupport:
    -9810844839
    -0238547492