
build:
  version: "2.0"

loans:
  message: "welcome to bankAccountManagement loans related prod APIs"
  contactDetails:
    name : "saroj khatiwada"
    email : "sarojkhatiwada1999@gmail.com"
  onCallSupport:
    -9810844839
    -0238547492