build:
  version: "1.0"

loans:
  message: "Welcome to bankAccountManagement loans related qa APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@bankAccountManagement.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384