services:
  accountsdb:
    container_name: accounts_container
    environment:

      MYSQL_DATABASE: accountsdb
    ports:
      - "3306:3306"

    extends:
      file: common-config.yml
      service: microservice_db_config

  loansdb:
    container_name: loans_container
    environment:
      MYSQL_DATABASE: loansdb
    ports:
      - "3307:3306"
    extends:
      file: common-config.yml
      service: microservice_db_config

  cardsdb:

    container_name: cards_container
    environment:

      MYSQL_DATABASE: cardsdb
    ports:
      - "3308:3306"

    extends:
      file: common-config.yml
      service: microservice_db_config
  configserver:
    image: "sarojkhatiwada/configserver"
    container_name: configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  accounts:
    image: "sarojkhatiwada/accounts"
    container_name: accounts-container
    ports:
      - "8081:8081"
    depends_on:
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "sarojkhatiwada/loans"
    container_name: loans-container
    ports:
      - "8090:8090"
    depends_on:
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "sarojkhatiwada/cards"
    container_name: cards-container
    ports:
      - "9000:9000"
    depends_on:
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


networks:
  bank_account_management:
    driver: "bridge"