spring:
  application:
    name: "accounts"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071"


  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/accountsdb
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
