spring:
  application:
    name: "accounts"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071"


#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/accountsdb
#    username: ${MYSQL_USERNAME:root}
#    password: ${MYSQL_PASSWORD:password}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
# Configure H2 Database

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    h2:
      console:
        enabled: true


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  #        info.emv.enabled=true could be used to expose service information through an
  #  endpoint like version ,description name etc.., making it accessible for monitoring or integration with other services.

  info:
    env:
      enabled: true
#     this is used to unregister the service from the eureka server after shutdown
  endpoint:
    shutdown:
      enabled: true
#      this is used to expose shutdown related apis
endpoints:
  shutdown:
    enabled: true

#by setting this tells the Eureka client to register the IP address
#  of the instance instead of its hostname when registering with the Eureka server
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

#this information will be displayed in the eureka server dahsboard
#so this provides the information about the account microservice
info:
  app:
    name: "accounts"
    description: "Bank_Account_Management accounts Application"
    version: "1.0.0"
